/**
 * Defining commands here
 */
module.exports = {
	_base: {
		maintainer: true,
		aliases: ["basic", "baase"],
		usage: `<user>`,
		description: `Eggs`,
		subcommands: ["array", "of", "subcommands"],
	},
	ping: {
		maintainer: false,
		usage: ``,
		description: `Pings the bot. What else?!`,
		aliases: ["pang"],
		category: `V-Bot 🤖`,
	},
	eval: {
		aliases: ["ev"],
		maintainer: true,
		usage: `<code>`,
		description: `Evaluates some code in the context of the bot.`,
		category: `V-Bot 🤖`,
	},
	kingdgrizzle: {
		aliases: ["kingd", "kdg"],
		maintainer: false,
		usage: ``,
		description: `KingDGrizzle but cringy.`,
		category: `Fun 🎪`,
	},
	reload: {
		maintainer: true,
		usage: `"all" or <...command>`,
		description: `Reloads a command or all the configs and the commands`,
		aliases: ["r"],
		category: `V-Bot 🤖`,
	},
	tttie: {
		maintainer: false,
		aliases: ["almighty-b1nzy-pinger"],
		usage: `[hail]`,
		description: `TTtie is not the god`,
		category: `Fun 🎪`,
	},
	vlag: {
		maintainer: false,
		aliases: ["vlad"],
		usage: ``,
		description: `All hail Vlag!`,
		category: `Fun 🎪`,
	},
	vaporwave: {
		aliases: ["vapor", "wave"],
		maintainer: false,
		usage: `[text]`,
		description: `Make some sick ass Ａ　Ｅ　Ｓ　Ｔ　Ｈ　Ｅ　Ｔ　Ｉ　Ｃ　Ｓ text.`,
		category: `Utility 🔦`,
	},
	tom: {
		aliases: ["dnomaid", "badfish"],
		maintainer: false,
		usage: ``,
		description: `Tells dnomaid he's a bad fish.. \\🐟`,
		category: `Fun 🎪`,
	},
	stroke: {
		maintainer: false,
		usage: `<...user>`,
		description: `Stroke someone. Why not?!`,
		aliases: ["strake", "strokes"],
		category: `Fun 🎪`,
	},
	gay: {
		aliases: ["gey", "guy"],
		maintainer: false,
		usage: `[<...user>]`,
		description: `Is someone gay? (It doesn't give a rating)`,
		category: `Fun 🎪`,
	},
	bantergaming: {
		aliases: ["banter", "eggs", "egg"],
		maintainer: false,
		usage: ``,
		description: `Banter lieks eggz`,
		category: `Fun 🎪`,
	},
	bless: {
		aliases: ["blessup", "blesses", "bloss"],
		maintainer: false,
		usage: `[<...user>]`,
		description: `Vlag the God blesses you (or others too!)`,
		category: `Fun 🎪`,
	},
	fixit: {
		aliases: ["fix", "fix-it"],
		maintainer: false,
		usage: ``,
		description: `Fix what now?`,
		category: `Fun 🎪`,
	},
	gabvsauttaja: {
		aliases: ["auttajaisbetter", "gabsucks", "switch_to_auttaja", "switch_to_gawesomebot"],
		maintainer: false,
		usage: ``,
		description: `Uhm.. Do we really need a command to explain that both bots are good?!`,
		category: `Fun 🎪`,
	},
	gellatio: {
		aliases: ["gelato", "italianicecream"],
		maintainer: false,
		usage: ``,
		description: `Gellatio is a gay cup of ice cream.`,
		category: `Fun 🎪`,
	},
	gordon: {
		aliases: ["ramsey", "ramsay"],
		maintainer: false,
		usage: ``,
		description: `He's comming after you.. 🤔`,
		category: `Fun 🎪`,
	},
	hack: {
		aliases: ["h4x0r", "1337"],
		maintainer: false,
		usage: ``,
		description: `Hack the mainframe! 1337 style!`,
		category: `Fun 🎪`,
	},
	howmany: {
		aliases: ["howmuch", "what"],
		maintainer: false,
		usage: `<commands> or <usage>`,
		description: `Shows you the usage amount of the bot or the amount of commands present in the bot!`,
		subcommands: ["commands", "cmds", "usage", "usages"],
		category: `Utility 🔦`,
	},
	negative: {
		aliases: ["negativecommencer"],
		maintainer: false,
		usage: ``,
		description: `Negative is getting expose 💯`,
		category: `Fun 🎪`,
	},
	jaffa: {
		aliases: ["jaffameme"],
		maintainer: false,
		usage: ``,
		description: `Something something, Vlad isn't creative, and if you bully him something something.`,
		category: `Fun 🎪`,
	},
	pray: {
		aliases: ["prayers", "praying", "pray_to_vlag"],
		maintainer: false,
		usage: ``,
		description: `Pray to God Vlag!`,
		category: `Fun 🎪`,
	},
	josh: {
		aliases: ["st1ing", "sting"],
		maintainer: false,
		usage: ``,
		description: `Hail the Smol Lund God or something idfk..`,
		category: `Fun 🎪`,
	},
	haden: {
		aliases: ["handu", "hoodiny"],
		maintainer: false,
		usage: ``,
		description: `Admires Haden's underwear... I mean shows you how good his underwear is.. Yeah..`,
		category: `Fun 🎪`,
	},
	sorarin: {
		aliases: ["badpainter", "fingering", "soraron", "ron", "rin"],
		maintainer: false,
		usage: ``,
		description: `Sorarin likes pussy, what more?!`,
		category: `Fun 🎪`,
	},
	lazor: {
		aliases: ["lazor"],
		maintainer: false,
		usage: ``,
		description: `Something something, bullshit claims, something something`,
		category: `Fun 🎪`,
	},
	minecraft: {
		aliases: ["mc", "mine", "craft"],
		maintainer: false,
		usage: ``,
		description: `It's Minecraft day bro.`,
		category: `Fun 🎪`,
	},
	quake: {
		aliases: ["annsquake", "arseshake", "quake_propaganda"],
		maintainer: false,
		usage: ``,
		description: `Annsquake is actually safe!`,
		category: `Fun 🎪`,
	},
	spank: {
		aliases: ["spankin", "spanking", "spunk"],
		maintainer: false,
		usage: `<...user>`,
		description: `Spanks users. Just the way you like it!`,
		category: `Fun 🎪`,
	},
	hail: {
		aliases: ["heil"],
		maintainer: false,
		usage: `[<user>]`,
		description: `Hail Vlag!`,
		category: `Fun 🎪`,
	},
	help: {
		aliases: ["h"],
		maintainer: false,
		usage: `[<command>]`,
		description: `Gives help for the bot!`,
		category: `V-Bot 🤖`,
	},
};
